### ISSUE TITLE
Question: Can translations be used as regular strings instead of components?

### ISSUE THREAD

**Issue by sjerzykiewicz** [c00/svelte-translate#1]
Hello,
I'm working with translations in my SvelteKit project and would like to pass translated strings directly into some TypeScript functions. Is there a way to use the translations as plain strings rather than as components? If so, could you please provide guidance on how to achieve this?

Thank you for your help!

**Comment by c00** [comment]
Absolutely. I see there is no example in the readme, but there is in one in the [examples](https://github.com/c00/svelte-translate/blob/main/src/lib/demos/BasicWithFunction.svelte) in the repo.

You can get the translate function from the context, and just call it with a string:

```svelte
<script lang="ts">
  import { getContext } from 'svelte';
  import { CONTEXT_KEY, type SvelteTranslate } from 'sveltekit-translate';

  const { t } = getContext<SvelteTranslate>(CONTEXT_KEY);

  function doThing() {
    const someTranslation = $t('yourpath.to.translation');
    console.log('Translated text:', someTranslation);
  }
</script>
<!-- or in the html -->
<h1>{$t('my-page.title')}</h1>
```

So this way you can also use it in attributes, pass it to functions, and do whatever you want with it.

**Comment by sjerzykiewicz** [comment]
Thank you so much for the quick and helpful response! I completely missed the demos folder in the repo—my bad. The explanation makes perfect sense now, and it's great to know that I can use the translate function like this.

Thanks again for the clarification!
